version: '3.1'

services:
  drupal:
    image: drupal:8.2
    ports:
      - '8080:80'
    volumes:
      - drupal-modules:/var/www/html/modules
      - durpal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
      - drupal-sites:/var/www/html/sites

  database:
    image: postgres:12.1
    secrets:
      - psql_user
      - psql_password
    environment:
      - POSTGRES_USER_FILE=/run/secrets/psql_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/psql_password
    volumes:
      - drupal-data:/var/lib/postgresql/data

secrets:
  psql_user:
    external: true
  psql_password: 
    external: true

volumes:
  drupal-modules:
  durpal-profiles:
  drupal-themes:
  drupal-sites:
  drupal-data: