apiVersion: v1
kind: Service
metadata:
  name: k8s-service
spec:
  type: LoadBalancer
  selector:
    app: sample-k8s
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80
  sessionAffinity: None